/**
 * 采集内容：把 docs-resources/*.md 与 wiki/*.md 复制进 src/content/{docs,wiki}/，
 * 并生成 index.json（每条 {slug,title,group}，含 wiki 精选排序 + docs 分组）。
 * 容错：wiki 源目录缺失（如 Netlify CI 无 _scratch）时跳过复制、复用已提交快照。
 * 幂等：每次清空重建 content 目录。
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const SHOWCASE = path.resolve(__dirname, '..')
const REV = path.resolve(SHOWCASE, '..')                 // rev-agent
const DOCS_SRC = path.resolve(REV, 'docs-resources')
const WIKI_SRC = path.resolve(REV, '..', '_scratch', 'wiki')
const CONTENT = path.resolve(SHOWCASE, 'src', 'content')

/** 从 md 抽第一个 # 标题作标题，退化用文件名。 */
function titleOf(md, slug) {
  const m = md.match(/^\s*#\s+(.+?)\s*$/m)
  return m ? m[1].replace(/[#*`]/g, '').trim() : slug
}

function copyMd(srcDir, destDir, { skipUnderscore = false } = {}) {
  fs.mkdirSync(destDir, { recursive: true })
  if (!fs.existsSync(srcDir)) {
    console.log(`[collect] 源缺失，跳过复制（复用快照）: ${srcDir}`)
    // 复用已存在快照
    return fs.existsSync(destDir) ? fs.readdirSync(destDir).filter((f) => f.endsWith('.md')) : []
  }
  // 清空旧快照再复制，保持与源一致
  for (const f of fs.readdirSync(destDir)) if (f.endsWith('.md')) fs.rmSync(path.join(destDir, f))
  const files = fs.readdirSync(srcDir).filter((f) => f.endsWith('.md') && (!skipUnderscore || !f.startsWith('_')))
  for (const f of files) fs.copyFileSync(path.join(srcDir, f), path.join(destDir, f))
  return files
}

const docFiles = copyMd(DOCS_SRC, path.join(CONTENT, 'docs'))
const wikiFiles = copyMd(WIKI_SRC, path.join(CONTENT, 'wiki'), { skipUnderscore: true })

// wiki 精选排序（其余按名追加）
const WIKI_ORDER = [
  'Home', 'Quickstart', 'Architecture', 'Mechanisms', 'Context-Memory-System',
  'Comparisons', 'Showcase-Benchmark-Questions', 'Iron-Laws',
  'Experiments-and-Findings', 'Onboarding-for-Agents', 'Roadmap',
]
// docs 分组前缀 → 组名（用于侧栏分组标题）
const DOC_GROUPS = [
  [/^框架化/, '框架化 · Framework'],
  [/^(上下文记忆|记忆系统)/, '记忆系统 · Memory'],
  [/^(混合后端|顺路发现)/, '混合后端 & 探索 · Hybrid'],
  [/^(pi-agent|多Agent)/, '多 Agent 协作 · Multi-agent'],
  [/^安全审计-(moded|攻击者画像|攻击机制|加固|破解类型|apk-2|静态|签名)/, '破解审计 · APK Crack Forensics'],
  [/^(安全审计|测试语料)/, '安全 & 语料 · Security'],
  [/^(LLM|如何给|feature-复盘|实跑记录)/, '协议 & 方法 · Protocol'],
]
function groupOf(slug) {
  for (const [re, name] of DOC_GROUPS) if (re.test(slug)) return name
  return '其它 · Misc'
}

function entries(files, dir, order) {
  const list = files.map((f) => {
    const slug = f.replace(/\.md$/, '')
    const md = fs.readFileSync(path.join(CONTENT, dir, f), 'utf-8')
    return { slug, file: f, title: titleOf(md, slug), group: dir === 'docs' ? groupOf(slug) : undefined, chars: md.length }
  })
  if (order) {
    list.sort((a, b) => {
      const ia = order.indexOf(a.slug), ib = order.indexOf(b.slug)
      return (ia < 0 ? 999 : ia) - (ib < 0 ? 999 : ib) || a.slug.localeCompare(b.slug)
    })
  } else {
    list.sort((a, b) => (a.group || '').localeCompare(b.group || '') || a.slug.localeCompare(b.slug))
  }
  return list
}

const index = {
  generatedNote: 'auto-generated by collect-content.mjs',
  docs: entries(docFiles, 'docs'),
  wiki: entries(wikiFiles, 'wiki', WIKI_ORDER),
}
fs.mkdirSync(CONTENT, { recursive: true })
fs.writeFileSync(path.join(CONTENT, 'index.json'), JSON.stringify(index, null, 2))
console.log(`[collect] docs=${index.docs.length} wiki=${index.wiki.length} → src/content/index.json`)
